package com.real.fudousan.favorite.vo;

import java.io.Serializable;
import java.util.Date;

import com.real.fudousan.estate.vo.Estate;
import com.real.fudousan.member.vo.Member;

/**
 * 찜하기 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Favorite implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 회원 ID. */
	private int memberId;

	/** 매물. */
	private Estate estate;

	/** DATE. */
	private Date creDate;

	public Favorite(){}
	
	public Favorite(int memberId, Estate estate, Date creDate) {
		super();
		this.memberId = memberId;
		this.estate = estate;
		this.creDate = creDate;
	}

	public int getMemberId() {
		return memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public Estate getEstate() {
		return estate;
	}

	public void setEstate(Estate estate) {
		this.estate = estate;
	}

	public Date getCreDate() {
		return creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	
	
	@Override
	public String toString() {
		return "Favorite [memberId=" + memberId + ", estate=" + estate + ", creDate=" + creDate + "]";
	}

}
