package com.real.fudousan.estate.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 도시 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MunicipalityCode implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** MunicipalityCode_ID. */
	private Integer municipalitycodeId;

	/** NAME. */
	private String codeName;

	public MunicipalityCode() {}

	public MunicipalityCode(Integer municipalitycodeId, String codeName) {
		super();
		this.municipalitycodeId = municipalitycodeId;
		this.codeName = codeName;
	}

	public Integer getMunicipalitycodeId() {
		return municipalitycodeId;
	}

	public void setMunicipalitycodeId(Integer municipalitycodeId) {
		this.municipalitycodeId = municipalitycodeId;
	}

	public String getCodeName() {
		return codeName;
	}

	public void setCodeName(String codeName) {
		this.codeName = codeName;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "MunicipalityCode [municipalitycodeId=" + municipalitycodeId + ", codeName=" + codeName + "]";
	}
	
	
	
}
