package com.real.fudousan.estate.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import com.real.fudousan.agency.vo.Agency;

/**
 * 거래 유형 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TransType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 거래 유형 ID. */
	private Integer transTypeId;

	/** 거래 유형 이름. */
	private String transName;
	
	

	public Integer getTransTypeId() {
		return transTypeId;
	}

	public void setTransTypeId(Integer transTypeId) {
		this.transTypeId = transTypeId;
	}

	public String getTransName() {
		return transName;
	}

	public void setTransName(String transName) {
		this.transName = transName;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public TransType() {
		super();
	}

	public TransType(Integer transTypeId, String transName) {
		super();
		this.transTypeId = transTypeId;
		this.transName = transName;
	}

	@Override
	public String toString() {
		return "TransType [transTypeId=" + transTypeId + ", transName=" + transName + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((transTypeId == null) ? 0 : transTypeId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TransType other = (TransType) obj;
		if (transTypeId == null) {
			if (other.transTypeId != null)
				return false;
		} else if (!transTypeId.equals(other.transTypeId))
			return false;
		return true;
	}
	
	
}
