package com.real.fudousan.reply.vo;

import java.io.Serializable;
import java.util.Date;

import com.real.fudousan.estate.vo.Estate;
import com.real.fudousan.member.vo.Member;

/**
 * 댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Reply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** REPLY_ID. */
	private Integer replyId;

	/** 매물 아이디. */
	private int estateId;

	/** 회원. */
	private Member member;

	/** TEXT. */
	private String text;

	/** DATE. */
	private Date creDate;

	public Integer getReplyId() {
		return replyId;
	}

	public void setReplyId(Integer replyId) {
		this.replyId = replyId;
	}

	public int getEstateId() {
		return estateId;
	}

	public void setEstateId(int estateId) {
		this.estateId = estateId;
	}

	public Member getMember() {
		return member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Date getCreDate() {
		return creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "Reply [replyId=" + replyId + ", estateId=" + estateId + ", member=" + member + ", text=" + text
				+ ", creDate=" + creDate + "]";
	}
	
	
}
