package com.real.fudousan.texture.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 텍스쳐 분류 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TextureType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** TEXTURE_TYPE_ID. */
	private Integer textureTypeId;

	/** NAME. */
	private String name;

	/** TEXT. */
	private String text;
}
