package com.real.fudousan.item.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 아이템 분류 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ItemType implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ITEM_TYPE_ID. */
	private Integer itemTypeId;

	/** NAME. */
	private String itemTypeName;

	public Integer getItemTypeId() {
		return itemTypeId;
	}

	public void setItemTypeId(Integer itemTypeId) {
		this.itemTypeId = itemTypeId;
	}

	public String getItemTypeName() {
		return itemTypeName;
	}

	public void setItemTypeName(String itemTypeName) {
		this.itemTypeName = itemTypeName;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public ItemType() {
		super();
	}

	public ItemType(Integer itemTypeId, String itmeTypeName) {
		super();
		this.itemTypeId = itemTypeId;
		this.itemTypeName = itmeTypeName;
	}

	@Override
	public String toString() {
		return "ItemType [itemTypeId=" + itemTypeId + ", itmeTypeName=" + itemTypeName + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemTypeId == null) ? 0 : itemTypeId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ItemType other = (ItemType) obj;
		if (itemTypeId == null) {
			if (other.itemTypeId != null)
				return false;
		} else if (!itemTypeId.equals(other.itemTypeId))
			return false;
		return true;
	}
}
