package com.real.fudousan.item.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.real.fudousan.roomitem.vo.RoomItem;

/**
 * 3D 방 내부 아이템 들 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Item implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ITEM_ID. */
	private Integer itemId;

	/** 아이템 분류. */
	private ItemType itemType;

	/** NAME. */
	private String itemName;

	/** TEXT. */
	private String text;

	/** FILE_DIRECTORY. */
	private String fileDirectory;
	
	/** MODEL_FILE_NAME. */
	private String modelFileName;

	/** 아이템 참고 사이트 목록. */
	private List<RefSite> refSiteSet;
	
	private double itemScale;
	
	private double itemRotateX;
	
	private double itemRotateY;
	
	private double itemRotateZ;
	
	private double itemX;
	
	private double itemY;
	
	private double itemZ;
	
	private String itemPreview;

	public Item() {
		super();
	}


	


	public Item(Integer itemId, ItemType itemType, String itemName, String text, String fileDirectory,
			String modelFileName, List<RefSite> refSiteSet, double itemScale, double itemRotateX, double itemRotateY,
			double itemRotateZ, double itemX, double itemY, double itemZ, String itemPreview) {
		super();
		this.itemId = itemId;
		this.itemType = itemType;
		this.itemName = itemName;
		this.text = text;
		this.fileDirectory = fileDirectory;
		this.modelFileName = modelFileName;
		this.refSiteSet = refSiteSet;
		this.itemScale = itemScale;
		this.itemRotateX = itemRotateX;
		this.itemRotateY = itemRotateY;
		this.itemRotateZ = itemRotateZ;
		this.itemX = itemX;
		this.itemY = itemY;
		this.itemZ = itemZ;
		this.itemPreview = itemPreview;
	}





	public Integer getItemId() {
		return itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	public ItemType getItemType() {
		return itemType;
	}

	public void setItemType(ItemType itemType) {
		this.itemType = itemType;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getFileDirectory() {
		return fileDirectory;
	}

	public void setFileDirectory(String fileDirectory) {
		this.fileDirectory = fileDirectory;
	}

	public String getModelFileName() {
		return modelFileName;
	}

	public void setModelFileName(String modelFileName) {
		this.modelFileName = modelFileName;
	}

	public List<RefSite> getRefSiteSet() {
		return refSiteSet;
	}

	public void setRefSiteSet(List<RefSite> refSiteSet) {
		this.refSiteSet = refSiteSet;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public double getItemScale() {
		return itemScale;
	}


	public void setItemScale(double itemScale) {
		this.itemScale = itemScale;
	}

	

	public double getItemRotateX() {
		return itemRotateX;
	}





	public double getItemX() {
		return itemX;
	}


	public void setItemX(double itemX) {
		this.itemX = itemX;
	}


	public double getItemY() {
		return itemY;
	}


	public void setItemY(double itemY) {
		this.itemY = itemY;
	}


	public double getItemZ() {
		return itemZ;
	}


	public void setItemZ(double itemZ) {
		this.itemZ = itemZ;
	}


	public void setItemRotateX(double itemRotateX) {
		this.itemRotateX = itemRotateX;
	}





	public double getItemRotateY() {
		return itemRotateY;
	}





	public void setItemRotateY(double itemRotateY) {
		this.itemRotateY = itemRotateY;
	}





	public double getItemRotateZ() {
		return itemRotateZ;
	}





	public void setItemRotateZ(double itemRotateZ) {
		this.itemRotateZ = itemRotateZ;
	}



	public String getItemPreview() {
		return itemPreview;
	}





	public void setItemPreview(String itemPreview) {
		this.itemPreview = itemPreview;
	}





	@Override
	public String toString() {
		return "Item [itemId=" + itemId + ", itemType=" + itemType + ", itemName=" + itemName + ", text=" + text
				+ ", fileDirectory=" + fileDirectory + ", modelFileName=" + modelFileName + ", refSiteSet=" + refSiteSet
				+ ", itemScale=" + itemScale + ", itemRotateX=" + itemRotateX + ", itemRotateY=" + itemRotateY
				+ ", itemRotateZ=" + itemRotateZ + ", itemX=" + itemX + ", itemY=" + itemY + ", itemZ=" + itemZ
				+ ", itemPreview=" + itemPreview + "]";
	}





	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itemId == null) ? 0 : itemId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Item other = (Item) obj;
		if (itemId == null) {
			if (other.itemId != null)
				return false;
		} else if (!itemId.equals(other.itemId))
			return false;
		return true;
	}
	
	
}
