package com.real.fudousan.advice.vo;

import java.io.Serializable;
import java.util.Date;

import com.real.fudousan.member.vo.Member;
import com.real.fudousan.room.vo.Room;

/**
 * 조언 리스트 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Advice implements Serializable {
	/**
	 * 요청 중
	 */
	public static int REQUEST = 0;
	/**
	 * 요청 허가
	 */
	public static int CONFIRMED = 1;
	/**
	 * 요청 취소
	 */
	public static int CANCEL = 2;
	/**
	 * 요청 거부
	 */
	public static int DENIED = 3;

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 신청한 회원. */
	private int requestMemberId;

	/** 신청받은 회원. */
	private int requestedMemberId;

	/** 3D 방. */
	private Room room;

	/** DATE. */
	private Date creDate;

	/** ID. */
	private String id;

	/** REQUEST_DATE. */
	private Date requestDate;

	/** STATE. */
	private int state;

	public Advice() {	}

	public Advice(int requestMemberId, int requestedMemberId, Room room, Date creDate, String id, Date requestDate,
			int state) {
		super();
		this.requestMemberId = requestMemberId;
		this.requestedMemberId = requestedMemberId;
		this.room = room;
		this.creDate = creDate;
		this.id = id;
		this.requestDate = requestDate;
		this.state = state;
	}

	public int getRequestMemberId() {
		return requestMemberId;
	}

	public void setRequestMemberId(int requestMemberId) {
		this.requestMemberId = requestMemberId;
	}

	public int getRequestedMemberId() {
		return requestedMemberId;
	}

	public void setRequestedMemberId(int requestedMemberId) {
		this.requestedMemberId = requestedMemberId;
	}

	public Room getRoom() {
		return room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	public Date getCreDate() {
		return creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getRequestDate() {
		return requestDate;
	}

	public void setRequestDate(Date requestDate) {
		this.requestDate = requestDate;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "Advice [requestMemberId=" + requestMemberId + ", requestedMemberId=" + requestedMemberId + ", room="
				+ room + ", creDate=" + creDate + ", id=" + id + ", requestDate=" + requestDate + ", state=" + state
				+ "]";
	}

	
}
