package com.real.fudousan.memberfile.vo;

import java.io.Serializable;
import java.util.Date;

import com.real.fudousan.member.vo.Member;

/**
 * 디자이너 프로필 파일 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MemberFile implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** MEMBER_FILE_ID. */
	private Integer memberFileId;

	/** 회원 아이디. */
	private int memberId;

	/** 원래 파일 이름. */
	private String originName;

	/** 서버 파일 이름. */
	private String serverName;

	/** DATE. */
	private Date creDate;

	/** TITLE. */
	private String title;

	/** TEXT. */
	private String text;
}
