package com.real.fudousan.member.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.real.fudousan.advice.vo.Advice;
import com.real.fudousan.agency.vo.Agency;
import com.real.fudousan.favorite.vo.Favorite;
import com.real.fudousan.memberfile.vo.MemberFile;
import com.real.fudousan.reply.vo.Reply;
import com.real.fudousan.room.vo.Room;
import com.real.fudousan.texture.vo.Texture;

/**
 * 회원 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Member implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** MEMBER_ID. */
	private Integer memberId;

	/** EMAIL. */
	private String email;

	/** PASSWORD. */
	private String password;

	/** 전화번호. */
	private String phone;

	/** 사진. */
	private String picture;

	/** 소개. */
	private String text;

	/** 가입 날. */
	private Date creDate;

	/** 탈퇴 날. */
	private Date delDate;

	/** 권한. */
	private Permission permission;

	/** 디자이너 유무. */
	private Integer designer;
	
	/** MEMBER_NAME. */
	private String memberName;

	public Integer getMemberId() {
		return memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPicture() {
		return picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Date getCreDate() {
		return creDate;
	}

	public void setCreDate(Date creDate) {
		this.creDate = creDate;
	}

	public Date getDelDate() {
		return delDate;
	}

	public void setDelDate(Date delDate) {
		this.delDate = delDate;
	}

	public Permission getPermission() {
		return permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

	public Integer getDesigner() {
		return designer;
	}

	public void setDesigner(Integer designer) {
		this.designer = designer;
	}

	public String getMemberName() {
		return memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Member() {
		super();
	}
	

	public Member(Integer memberId, String email, String password, String phone, String picture, String text,
			Date creDate, Date delDate, Permission permission, Integer designer, String memberName) {
		super();
		this.memberId = memberId;
		this.email = email;
		this.password = password;
		this.phone = phone;
		this.picture = picture;
		this.text = text;
		this.creDate = creDate;
		this.delDate = delDate;
		this.permission = permission;
		this.designer = designer;
		this.memberName = memberName;
	}

	@Override
	public String toString() {
		return "Member [memberId=" + memberId + ", email=" + email + ", password=" + password + ", phone=" + phone
				+ ", picture=" + picture + ", text=" + text + ", creDate=" + creDate + ", delDate=" + delDate
				+ ", permission=" + permission + ", designer=" + designer + ", memberName : " + memberName + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((memberId == null) ? 0 : memberId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Member other = (Member) obj;
		if (memberId == null) {
			if (other.memberId != null)
				return false;
		} else if (!memberId.equals(other.memberId))
			return false;
		return true;
	}
	
	
}
