package com.real.fudousan.member.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 권한 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Permission implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** PERMISSION_ID. */
	private Integer permissionId;

	/** NAME. */
	private String name;

	
	
	public Permission() {
		super();
	}

	public Permission(Integer permissionId, String name) {
		super();
		this.permissionId = permissionId;
		this.name = name;
	}

	public Integer getPermissionId() {
		return permissionId;
	}

	public void setPermissionId(Integer permissionId) {
		this.permissionId = permissionId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return "Permission [permissionId=" + permissionId + ", name=" + name + "]";
	}
	
	
	
	
	
}
